# create a docker-compose.yml file
version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/home/lucas/fileserver
    ports:
      - "3000:3000"
    links: 
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  #   volumes_from:
  #     - mongodata
  # mongodata:
  #   image: tianon/true
  #   volumes:
  #     - /data/db
  #   command: echo 'Data container'
